version: "3.9"
services:
  redis:
    networks:
      - movierama_net
    image: "redis:alpine"
    restart: unless-stopped
    container_name: redis_movierama
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
  pgsql:
    networks:
      - movierama_net
    image: postgres
    restart: unless-stopped
    container_name: pgsql_movierama
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: apJ4D@7E(Aw2sm9T
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  movierama.webapp:
    networks:
      - movierama_net
    image: movierama.webapp
    restart: unless-stopped
    ports:
      - "5195:8080"
    depends_on:
      - redis
      - pgsql
    build:
      context: .
      dockerfile: ./src/app/MovieRama.WebApp/Dockerfile

volumes:
  redis:
  pgdata:
    
networks:
  movierama_net:
    driver: bridge
